# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: jmeyer1980.MtgaPlayByPlay
PackageVersion: 0.4.0
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-08-13
InstallModes:
- interactive
- silent
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: mtga-pbp.exe
    PortableCommandAlias: mtga-pbp
  InstallerUrl: https://github.com/jmeyer1980/mtga-play-by-play/releases/download/v0.4.0/mtga-pbp-v0.4.0-win-x64.zip
  InstallerSha256: 83D391189727C5CBE3028AD2C979A1C89136A1454F58689703DD64AA03BE9AB3
ManifestType: installer
ManifestVersion: 1.12.0
