# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: jmeyer1980.MtgaPlayByPlay
PackageVersion: 0.3.1
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-08-12
InstallModes:
- interactive
- silent
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: mtga-pbp.exe
    PortableCommandAlias: mtga-pbp
  InstallerUrl: https://github.com/jmeyer1980/mtga-play-by-play/releases/download/v0.3.1/mtga-pbp-v0.3.1-win-x64.zip
  InstallerSha256: C7D69692B5DBB09D3DA51E5EABA00D15038DE6EBEEAC295D8759B952FD71943A
ManifestType: installer
ManifestVersion: 1.12.0
